// ═══════════════════════════════════════════════════
// ECOTRACK AI — CHALLENGES & BADGES DEFINITIONS
// ═══════════════════════════════════════════════════

export const DEFAULT_CHALLENGES = [
  {
    id: 'meatless-monday',
    title: 'Meatless Monday',
    description: 'Go meat-free every Monday for a week. Choose vegetarian or vegan meals to reduce your carbon footprint.',
    icon: '🥗',
    duration: 7,
    category: 'food',
    co2Savings: 6,
    difficulty: 'Easy',
    joined: false,
    progress: 0,
    startDate: null,
    completed: false,
  },
  {
    id: 'bike-to-work',
    title: 'Bike to Work',
    description: 'Replace your car commute with biking or walking for 5 days. Great for fitness and the planet!',
    icon: '🚲',
    duration: 5,
    category: 'transport',
    co2Savings: 12,
    difficulty: 'Medium',
    joined: false,
    progress: 0,
    startDate: null,
    completed: false,
  },
  {
    id: 'energy-saver',
    title: 'Energy Saver',
    description: 'Reduce your electricity usage by 20% this week. Turn off lights, unplug devices, and use natural light.',
    icon: '💡',
    duration: 7,
    category: 'electricity',
    co2Savings: 8,
    difficulty: 'Medium',
    joined: false,
    progress: 0,
    startDate: null,
    completed: false,
  },
  {
    id: 'zero-waste-day',
    title: 'Zero Waste Day',
    description: 'Go an entire day without buying any new items. Use what you have and avoid unnecessary shopping.',
    icon: '♻️',
    duration: 1,
    category: 'shopping',
    co2Savings: 3,
    difficulty: 'Easy',
    joined: false,
    progress: 0,
    startDate: null,
    completed: false,
  },
  {
    id: 'public-transit-hero',
    title: 'Public Transit Hero',
    description: 'Use only public transit (bus or train) for all your commuting needs for a full week.',
    icon: '🚌',
    duration: 7,
    category: 'transport',
    co2Savings: 15,
    difficulty: 'Hard',
    joined: false,
    progress: 0,
    startDate: null,
    completed: false,
  },
  {
    id: 'vegan-week',
    title: 'Vegan Week',
    description: 'Eat entirely plant-based meals for 7 days straight. Discover delicious vegan recipes along the way!',
    icon: '🌱',
    duration: 7,
    category: 'food',
    co2Savings: 20,
    difficulty: 'Hard',
    joined: false,
    progress: 0,
    startDate: null,
    completed: false,
  },
];

export const DEFAULT_BADGES = [
  {
    id: 'first-step',
    title: 'First Step',
    emoji: '🌱',
    description: 'Log your first activity',
    condition: 'Log 1 activity',
    earned: false,
    earnedDate: null,
  },
  {
    id: 'on-fire',
    title: 'On Fire',
    emoji: '🔥',
    description: 'Maintain a 3-day logging streak',
    condition: '3-day streak',
    earned: false,
    earnedDate: null,
  },
  {
    id: 'week-warrior',
    title: 'Week Warrior',
    emoji: '⚡',
    description: 'Maintain a 7-day logging streak',
    condition: '7-day streak',
    earned: false,
    earnedDate: null,
  },
  {
    id: 'plant-powered',
    title: 'Plant Powered',
    emoji: '🥗',
    description: 'Log 10 vegetarian or vegan meals',
    condition: '10 plant meals',
    earned: false,
    earnedDate: null,
  },
  {
    id: 'pedal-pusher',
    title: 'Pedal Pusher',
    emoji: '🚲',
    description: 'Log 5 bike or walk trips',
    condition: '5 bike/walk trips',
    earned: false,
    earnedDate: null,
  },
  {
    id: 'challenge-champion',
    title: 'Challenge Champion',
    emoji: '🏆',
    description: 'Complete 3 eco challenges',
    condition: 'Complete 3 challenges',
    earned: false,
    earnedDate: null,
  },
  {
    id: 'eco-legend',
    title: 'Eco Legend',
    emoji: '🌍',
    description: 'Achieve an EcoScore of 90 or above',
    condition: 'EcoScore 90+',
    earned: false,
    earnedDate: null,
  },
];
